### ISSUE TITLE
Fine Tuning

### ISSUE THREAD

**Issue by elgizabbasov** [Tech-Start-UCalgary/Aquavolution#169]
Remove the diamonds from the rooms and add bubbles animation
A little less number of enemies? At least in the first few rooms
Depth showing distance to final room? (You are xxxx meters away/above!)
Number of vertical rooms a bit too much
Enemy death animation
Aesthetic changes to ‘Reach 40 points’ - Transparent in the middle

Food:
Limit so we dont have too much
Enemies:
KnockbackPower reduce a bit?
Player
Get rid of player increasing in size
Player accelerates too fast - no limit/add a limit

**Comment by Anidion** [comment]
- [ ] Remove the diamonds from the rooms and add bubbles animation
- [ ] A little less number of enemies? At least in the first few rooms
- [ ] Depth showing distance to final room? (You are xxxx meters away/above!)
- [ ] Number of vertical rooms a bit too much
- [ ] Enemy death animation
- [ ] Aesthetic changes to ‘Reach 40 points’ - Transparent in the middle

Food:
- [ ] Limit so we dont have too much
Enemies:
- [ ] KnockbackPower reduce a bit?
Player
- [ ] Get rid of player increasing in size
- [ ] Player accelerates too fast - no limit/add a limit
